### ISSUE TITLE
コードブロックが反映されてない

### ISSUE THREAD

**Issue by Shirashoji** [Stack-Programing-Community/stack-tutorial#10]
コードブロックがサイト側でうまく表示されていない。

ドキュメント：
https://stack-community.github.io/stack-tutorial/sf-calculator/

Markdown：
https://github.com/stack-community/stack-tutorial/blob/main/contents/article/sf-calculator/sf-calculator.md

**Comment by Yokohama-Miyazawa** [comment]
このサイトはCSSにbootstrap4系を使っていて、複数行のコードは`<pre>`タグで囲まれるようになっています。
元々のbootstrap4での`<pre>`の仕様が、背景色は変わらず枠線もないものになっているようです。
https://getbootstrap.jp/docs/4.1/content/code/#code-blocks

したがって、見やすくするためには追加でstyleを設定する必要があります。

**Comment by Yokohama-Miyazawa** [comment]
https://github.com/stack-community/stack-tutorial/pull/11
