### ISSUE TITLE
説明のスクロールについて

### ISSUE THREAD

**Issue by ghost** [Stack-Programing-Community/stack-tutorial#5]
説明エリアの文章が多い場合には下の文章を見る為にスクロールするのですが、
右のオンライン実行環境も同時にスクロールしてしまうため、プログラムの入力がしにくく大変使いにくい状況です。
|スクロール前|スクロール後|
|-|-|
|![image](https://github.com/Stack-Programing-Community/stack-tutorial/assets/122075081/b4286a5b-2728-4067-86ad-856e8ed3d8e6)|![image](https://github.com/Stack-Programing-Community/stack-tutorial/assets/122075081/14b83451-f880-47a6-985c-ddad94fe4cbb)|

私はその問題に対処しようと試みたのですが、なぜかCSSが反映されず上手くいきませんでした。

SvelteKitに詳しい方、この問題に対処お願い致します

**Comment by Yokohama-Miyazawa** [comment]
修正しました。ご確認お願いします。
https://github.com/Stack-Programing-Community/stack-tutorial/pull/6
